# docker-compose.yml
version: "3.7"

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # GRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage # Persistent storage
    environment:
      - QDRANT_ALLOW_RECOVERY=true
      - QDRANT_STORAGE_PATH=/qdrant/storage
